### PR TITLE
doc: Document footgun about the usage of (large) numbers

### PR DESCRIPTION
**Pull request by kyranet**
Fixes https://github.com/tc39/proposal-bigint/issues/170

### CODE REVIEW

**Comment by kyranet** [comment]
Done in b4ca3ae, thanks you for reminding me!

**Comment by kyranet** [comment]
Sure! Though I do not know where to place this, as the entire "gotchas" section is missing in the [`BigInt` MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

**Comment by littledan** [comment]
I see, i'm not sure how this should be organized, cc @sarahGP @eichi3

**Comment by sarahgp** [comment]
I've been putting the Gotchas into a Usage Recommendations section or orange or pink note & warning boxes as appropriate.

It looks as though this would fit into Usage Recommendations. I might add a note about what's actually happening (representing the value as a number means it is losing precision before it is coerced and that is why you will prefer a string) and use less value-laden descriptors (eg: `roundedVal`, `preservedVal` over `bad` and `good`.

As I mentioned in another thread, there _are_ programmatic reasons someone might use the `BigInt` constructor on a `Number`, e.g. to coerce smaller values for interop with `BigInt`s, so I think it is important to make it clear what the problem is here and not fall back on "only coerce strings" as a blanket recommendation.

**Comment by littledan** [comment]
Good point. I agree there are important use cases (though I would still like to discourage certain kinds of "interop" patterns). Do you have any suggestions for tweaking this wording to make it not sound overly broad?

**Comment by sarahgp** [comment]
Other than `roundedVal` `preservedVal`? Or is there other wording you're asking about?

Overall, if you suggest to people a pattern plus reasoning, you give them tools to avoid tricky patterns and to extend that knowledge into other corners. I don't think there's anything wrong with saying "prefer strings or literals because otherwise you may lose precision" and then showing examples of that. I just don't think we need to call things _bad_ to make that point and that value words like that contribute to an atmosphere of morality around choices that can be alienating to folks, especially in documentation.

**Comment by littledan** [comment]
Right, thanks for the explanation. @kyranet, would you be interested in making this naming change and clarification?

**Comment by kyranet** [comment]
I can try when I get home 👍

**Pull request merged**
